POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "a@b.c",
  "password": "ciao",
  "rememberMe": true
}

###

POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
  "id": "5653ea02-0307-4340-9ce7-28a5138b61ae",
  "email": "a@b.c",
  "password": "drowssap",
  "name": "mario",
  "surname": "oiram",
  "country": {
    "name": "Venezuela",
    "flag": "🇻🇪",
    "code": "VE",
    "dial_code": "+58"
  }
}